apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: Employee-backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: swagatdevops/backend:latest
          ports:
            - containerPort: 8080