apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
     app: backend
spec:
 type: ClusterIP
 ports:
  - name: "backend-service"
    port: 8002
    targetPort: 8080  
 selector:
    app: backend
