apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      name: Employee-database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0
          ports:
            - containerPort: 3306