apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
     app: database
spec:
 type: ClusterIP
 ports:
  - name: "database-service"
    port: 3306
    targetPort: 3306  
 selector:
    app: database
