apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
     app: frontend
spec:
 type: NodePort
 ports:
  - name: "frontend-service"
    port: 8000
    targetPort: 80
    nodePort: 31000
 selector:
    app: frontend
